name: Build Docker Image

on:
    push:
      tags:
        - '*'
    pull_request:
      branches:
        - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: ğŸ™ Checkout code
        uses: actions/checkout@v4

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3


      # Step 3: Log in to Docker Hub
      - name: ğŸ³ Log in to Docker Hub
        if: github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Build and push the Docker image
      - name: ğŸ“¦ Build and push Docker image on push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          #push: ${{ github.event_name == 'push' }}
          #load: ${{ github.event_name == 'pull_request' }}
          load: false
          push: true
          tags: philippecharriere494/02-hello-scout-demo:${{ github.ref_name }}
          sbom: true
          provenance: true

      - name: ğŸ Build and push Docker image on PR
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          load: true
          push: false
          #push: ${{ github.event_name == 'push' }}
          #load: ${{ github.event_name == 'pull_request' }}
          tags: philippecharriere494/02-hello-scout-demo:${{ github.ref_name }}
          sbom: false
          provenance: false

      - name: ğŸ”ğŸ¤” Run Scout scan on PR
        if: github.event_name == 'pull_request'
        run: docker scout quickview

      - name: Compare to deployed image
        id: docker-scout-compare
        if: ${{ github.event_name == 'pull_request_target' }}
        uses: docker/scout-action@main
        with:
          command: compare
          image: philippecharriere494/02-hello-scout-demo:${{ github.ref_name }}
          only-severities: critical,high
          to-env: prod
          #platform: "linux/amd64"
          exit-code: true       
          summary: true


      - name: ğŸ” Run Scout scan on tag
        if: github.event_name == 'push'
        uses: docker/scout-action@v1
        with:
          command: quickview
          image: philippecharriere494/02-hello-scout-demo:${{ github.ref_name }}

      - name: ğŸ Analyze for critical and high CVEs
        id: docker-scout-cves
        if: ${{ github.event_name != 'pull_request_target' }}
        uses: docker/scout-action@v1
        with:
          command: cves
          image: philippecharriere494/02-hello-scout-demo:${{ github.ref_name }}
          sarif-file: sarif.output.json
          #platform: "linux/amd64"
          summary: true

      # Run Docker Scout analysis
      - name: ğŸª² Analyze for critical and high CVEs
        id: docker-scout-cves-2
        if: ${{ github.event_name != 'pull_request_target' }}
        uses: docker/scout-action@v1
        with:
          command: cves
          image: philippecharriere494/02-hello-scout-demo:${{ github.ref_name }}
          sarif-file: sarif.output.json
          #platform: "linux/amd64"
          summary: true

      # Step 6: Upload the report as an artifact
      - name: ğŸ“ Upload Scout Report
        id: upload-sarif
        if: ${{ github.event_name != 'pull_request_target' }}
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: sarif.output.json
        #uses: actions/upload-artifact@v4
        #with:
        #  name: docker-scout-report
        #  path: scout-report.txt